trigger: none
pr:
  - main

variables:
- group: elarande-general-params
- name: imageName
  value: seb-redirect
- name: dockerfilePath
  value: '$(Pipeline.Workspace)/github/Dockerfile'
- name: tag
  value: '$(Build.SourceVersion)'

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/test/docker-test.yml@cet-iac
    parameters:
      dockerComposeFilePaths:
        - '$(Pipeline.Workspace)/github/docker-compose-unit-tests.yml'
      dockerfilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)
